# __init__.py

from .ggplot import ggplot
from .ggtitle import ggtitle
from .aes import aes
from .themes import (
    theme_default,
    theme,
    theme_ggplot2,
    theme_nytimes,
    theme_minimal,
    theme_bbc,
    # theme_bw,
    theme_dark,
    theme_classic,
    theme_custom,
    element_text,
    element_line,
    element_rect,
)
from .facets import Facet, facet_wrap, facet_grid, label_value, label_both
from .coords import Coord, coord_flip, coord_polar, coord_cartesian, coord_sf
from .limits import xlim, ylim, lims
from .geoms import (
    geom_point,
    geom_line,
    geom_path,
    geom_bar,
    geom_col,
    geom_histogram,
    geom_boxplot,
    geom_smooth,
    geom_area,
    geom_density,
    geom_violin,
    geom_ribbon,
    geom_tile,
    geom_text,
    geom_errorbar,
    geom_segment,
    geom_step,
    geom_vline,
    geom_hline,
    geom_edgebundle,
    geom_searoute,
    geom_jitter,
    geom_rug,
    geom_abline,
    geom_contour,
    geom_contour_filled,
    geom_map,
    geom_sf,
    geom_range,
    geom_point_3d,
    geom_surface,
    geom_wireframe,
    geom_candlestick,
    geom_ohlc,
)
from .scales import (
    scale_x_continuous,
    scale_y_continuous,
    scale_color_manual,
    scale_color_brewer,
    scale_fill_gradient,
    scale_fill_manual,
    scale_fill_brewer,
    scale_fill_viridis_c,
    scale_shape_manual,
    scale_size,
    scale_x_log10,
    scale_y_log10,
    scale_x_date,
    scale_x_datetime,
    scale_x_rangeslider,
    scale_x_rangeselector,
    scale_color_gradient,
)
from .guides import labs, annotate, guides, guide_legend, guide_colorbar
from .positions import position_dodge, position_jitter, position_stack
from .utils import ggsave, ggsize
from .stats import *
from .datasets import data
from .map_data import map_data

__all__ = [
    "ggplot",
    "ggsave",
    "ggsize",
    "ggtitle",
    "aes",
    "theme_default",
    "theme",
    "theme_ggplot2",
    "theme_nytimes",
    "theme_minimal",
    "theme_bbc",
    # "theme_bw",
    "theme_dark",
    "theme_classic",
    "theme_custom",
    "element_text",
    "element_line",
    "element_rect",
    "Facet",
    "facet_wrap",
    "facet_grid",
    "label_value",
    "label_both",
    "Coord",
    "coord_flip",
    "coord_polar",
    "coord_cartesian",
    "coord_sf",
    "xlim",
    "ylim",
    "lims",
    "labs",
    "annotate",
    "guides",
    "guide_legend",
    "guide_colorbar",
    "position_dodge",
    "position_jitter",
    "position_stack",
    "geom_point",
    "geom_line",
    "geom_path",
    "geom_vline",
    "geom_hline",
    "geom_bar",
    "geom_col",
    "geom_histogram",
    "geom_boxplot",
    "geom_smooth",
    "geom_area",
    "geom_density",
    "geom_violin",
    "geom_ribbon",
    "geom_tile",
    "geom_text",
    "geom_errorbar",
    "geom_segment",
    "geom_step",
    "geom_edgebundle",
    "geom_searoute",
    "geom_jitter",
    "geom_rug",
    "geom_abline",
    "geom_contour",
    "geom_contour_filled",
    "geom_map",
    "geom_sf",
    "geom_range",
    "geom_point_3d",
    "geom_surface",
    "geom_wireframe",
    "geom_candlestick",
    "geom_ohlc",
    "scale_x_continuous",
    "scale_y_continuous",
    "scale_color_manual",
    "scale_color_brewer",
    "scale_fill_gradient",
    "scale_fill_manual",
    "scale_fill_brewer",
    "scale_fill_viridis_c",
    "scale_shape_manual",
    "scale_size",
    "scale_x_log10",
    "scale_y_log10",
    "scale_x_date",
    "scale_x_datetime",
    "scale_x_rangeslider",
    "scale_x_rangeselector",
    "scale_color_gradient",
    "stat_count",
    "stat_bin",
    "data",
    "map_data",
]
